version: "3.9"

services:

  stateless-auth-db:
    image: postgres:latest
    container_name: stateless-auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stateless_auth_data:/var/lib/postgresql
    networks:
      - auth-bridge
    restart: unless-stopped

  stateful-auth-db:
    image: postgres:latest
    container_name: stateful-auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - stateful_auth_data:/var/lib/postgresql
    networks:
      - auth-bridge
    restart: unless-stopped

  token-redis:
    image: redis:latest
    container_name: token-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - auth-bridge
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - stateless-auth-db
      - stateful-auth-db
    networks:
      - auth-bridge
    restart: unless-stopped

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    depends_on:
      - token-redis
    networks:
      - auth-bridge
    restart: unless-stopped
  stateless-auth-api:
    build: './stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: stateless-auth-db
      DB_PORT: 5432
      DB_NAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET_KEY: Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taWNyb3NzZXJ2aWNvcw==
    networks:
      - auth-bridge
  stateless-any-api:
    build: './stateless/stateless-any-api'
    container_name: stateless-any-api
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      JWT_SECRET_KEY: Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taWNyb3NzZXJ2aWNvcw==
    networks:
      - auth-bridge
  stateful-auth-api:
    build: './stateful/stateful-auth-api'
    container_name: stateful-auth-api
    depends_on:
      - stateful-auth-db
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
      DB_HOST: stateful-auth-db
      DB_PORT: 5432
      DB_NAME: auth-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: token-redis
      REDIS_PORT: 6379
    networks:
      - auth-bridge
  stateful-any-api:
    build: './stateful/stateful-any-api'
    container_name: stateful-any-api
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
      STATEFUL_AUTH_BASE_URL: http://stateful-auth-api:8082
    networks:
      - auth-bridge


networks:
  auth-bridge:
    driver: bridge


volumes:
  stateless_auth_data:
  stateful_auth_data:
  redis_data:
  pgadmin_data:
  redis_insight_data: